# Generated by Django 3.0.6 on 2020-05-18 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='records',
            name='bill_number',
        ),
    ]
