# Generated by Django 3.0.6 on 2020-05-18 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0002_remove_records_bill_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='records',
            name='time_difference',
            field=models.TimeField(editable=False, null=True),
        ),
    ]
